### ISSUE TITLE
Adjust hyperlinks from article to main theme of site

### ISSUE THREAD

**Issue by Portiva-O365** [Portiva-O365/webpart-rss#4]
It would be great to have the hyperlinks inherit the main theme color from the site. In the screenshot you see the hyperlinks from the RSS feed and the bottom is the main theme color. 

NOTE: Issue is reported by Kevin van Gelderen in the portfolio repo. Moved to here because issue is related to RSS web part and not the portfolio.

**Comment by equalizer999** [comment]
Can you please provide the suggested screenshot for some more clarification? Thanks!

**Comment by equalizer999** [comment]
@Portiva-O365 Fixed with commit #8
