### ISSUE TITLE
RSS Items 1 hour off

### ISSUE THREAD

**Issue by bercajimovic** [Portiva-O365/webpart-rss#7]
Hi.

Noticed that when news are posted from RSS the time is showing the post time with -1 hours.
![screenshot 2019-01-17 at 13 10 16](https://user-images.githubusercontent.com/46705090/51317960-44313d80-1a59-11e9-9573-91e05017a961.png)

News article:
![screenshot 2019-01-17 at 13 11 03](https://user-images.githubusercontent.com/46705090/51318090-9d00d600-1a59-11e9-8769-406d330eef63.png)

It might also be a good feature to be able to turn off the "pubdate" in webpart settings.

**Comment by mvdungen** [comment]
@bercajimovic: thanks for the issue. I will look into this, probably has something to do with the timestamp in RSS feed and the calculation to the current time. Also look into the feature request to toggle the visibility of the publication date. Keep you posted!

**Comment by equalizer999** [comment]
@bercajimovic; Described issue and enhancement should be fixed (#9)
